baseURL: "https://jmt.dev/"
title: jmt.dev️
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: jmt.dev
    description: "thoughts, findings, & projects by [@macintacos](/about/)"
    keywords: [blog]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: true
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false
    body_classes: "something"

    label:
        text: "jmt.dev"
        # icon: /apple-touch-icon.png
        # iconHeight: 35

    profileMode:
        enabled: false # defaults to true so need to be explicitly set

    homeInfoParams:
        Title: "thoughts, findings, & projects"
        Content: by [@macintacos](/about/)

    socialIcons:
        - name: twitter
          url: "https://twitter.com/macintacos"
        - name: email
          url: "mailto:julian.m.tor@gmail.com"
        - name: github
          url: "https://github.com/macintacos"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

markup:
     goldmark:
        renderer:
            unsafe: true

menu:
    main:
        - identifier: about
          name: 🧑‍💻 about
          url: /about/
          weight: 30
        - identifier: search
          name: 🔍️ find
          url: /search/
          weight: 40

outputs:
    home:
        - HTML
        - RSS
        - JSON # Required

